# Shinken reactionner with only reactionner role
# 
# VERSION		2.0.3

FROM		dguenault/shinken-base:2.0.3
MAINTAINER	David GUENAULT

ADD 		files/shinken-reactionner.conf /etc/supervisord.d/

EXPOSE 7769
