# Shinken broker with only broker role
# 
# VERSION		2.0.3

FROM		dguenault/shinken-base:2.0.3
MAINTAINER	David GUENAULT

ADD 		files/shinken-broker.conf /etc/supervisord.d/

EXPOSE 7772
EXPOSE 50000
EXPOSE 7767
